client_id:  "3MVG9A2kN3Bn17huURZ5FCDNVtZHfvgp_nx2kdrZBdq2p3wHtzMKt7ty3nc43srsIQhXanD2XHtnj5JXw_d_k"
client_secret: "8309548677418261257"
username: "morgan.wildermuth@gmail.com"
password: "1Microsoft1Git08Ha0tlKKzudWzY9UpyjT7"
debugging: true